version: "3.8"
services:
  nexus-api:
    build:
      context: ./nexus-api
      dockerfile: Dockerfile
    container_name: nexus_api
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=nexus_db
      - DB_USERNAME=secret
      - DB_PASSWORD=password
    depends_on:
      - mysql
      - meilisearch

    ports:
      - 8000:8000
    volumes:
      - ./nexus-api:/var/www

    networks:
      - nexus

  nexus-news:
    build:
      context: ./nexus-news
      dockerfile: Dockerfile
    container_name: nexus_news
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./nexus-news:/app/nexus-news
      - ./nexus-news:/app/nexus-news/node_modules
    depends_on:
      - nexus-api

    networks:
      - nexus

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nexus_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nexus

  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "sail-meilisearch:/meili_data"
    networks:
      - nexus
    # healthcheck:
    #   test:
    #     - CMD
    #     - wget
    #     - "--no-verbose"
    #     - "--spider"
    #     - "http://localhost:7700/health"
    #   retries: 3
    #   timeout: 5s

networks:
  nexus:
    driver: bridge

volumes:
  db-data: ~

  sail-meilisearch:
    driver: local
